apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/git-clone?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && ("git-clone".pathChanged() || "Dockerfile".pathChanged())
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: git-clone
    appstudio.openshift.io/component: git-clone
    pipelines.appstudio.openshift.io/type: build
  name: git-clone-on-push
  namespace: konflux-build-pipeli-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/konflux-build-pipeli-tenant/git-clone/git-clone:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  pipelineRef:
    name: git-clone-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-git-clone
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
